const router = require('express').Router()
const guestRouter = require('./guest')
const authRouter = require('./auth')
const weddingRouter = require('./wedding')
const invitationRouter = require('./invitation')
const eventRouter = require('./invitationforguest')
const commentRouter = require('./comment')
const { authentication } = require('../middlewares')
const { GuestController } = require('../controllers')

router.use('/', authRouter)
router.use('/events', eventRouter)
router.use('/comments', commentRouter)
router.patch('/guests/:id', GuestController.changeStatus)
router.post('/guests/payment', GuestController.guestPayment)
router.use(authentication)
router.use('/guests', guestRouter)
router.use('/weddings', weddingRouter)
router.use('/invitations', invitationRouter)

module.exports = router